from selenium.webdriver.common.by import By

class MainPageLocators:
    chart = (By.XPATH, '//div[@class="shopping_cart"]/a')
    sigh_in = (By.XPATH, '//div[@class="header_user_info"]/a')
    logo = (By.XPATH, '//img[@class="logo img-responsive"]')
    search_submit = (By.XPATH, '//form/input[@type="text"]')
    search_button = (By.XPATH, '//form/button[@type="submit"]')
    women_button = (By.XPATH, '//a[@title="Women"]')


class CartLocators:
    empty_cart = (By.XPATH, '//p[@class= "alert alert-warning"]')
    women_button = (By.XPATH, '//a[@title="Women"]')
    list_of_produkts = (By.XPATH, '//i[@class="icon-th-list"]')
    dress_add_to_cart = (By.XPATH, '//a[@data-id-product="1"]/span')
    proceed_to_check_out_1 = (By.XPATH, '//a[@title="Proceed to checkout"]/span')
    unit_price = (By.XPATH, '//li[@class="price"]')
    quantity_increase = (By.XPATH, '//i[@class="icon-plus"]')
    quantity_decrease = (By.XPATH, '//i[@class="icon-minus"]')
    quantity = (By.XPATH, '//td[@class="cart_quantity text-center"]/input[@type="hidden"]')
    total_product_price = (By.XPATH, '//td[@id="total_product"]')
    shipping = (By.XPATH, '//td[@id="total_shipping"]')
    tax = (By.XPATH, '//td[@id="total_tax"]')
    total_price = (By.XPATH, '//span[@id="total_price"]')
    proceed_to_check_out_2 = (By.XPATH, '//p[@class="cart_navigation clearfix"]//span')
    new_address = (By.XPATH, '//a[@title="Add"]/span')
    address = (By.XPATH, '//input[@data-validate="isAddress" and @name="address1"]')
    city = (By.XPATH, '//input[@data-validate="isCityName" and @name="city"]')
    state = (By.XPATH, '//select[@name="id_state"]')
    zip_code = (By.XPATH, '//input[@id="postcode"]')
    home_phone = (By.XPATH, '//input[@id="phone"]')
    mobile_phone = (By.XPATH, '//input[@id="phone_mobile"]')
    save_button = (By.XPATH, '//button[@name="submitAddress"]/span')
    proceed_to_check_out_3 = (By.XPATH, '//button[@name="processAddress"]/span')
    terms_and_delivery_confirmation = (By.XPATH, '//input[@type="checkbox"]')
    proceed_to_check_out_4 = (By.XPATH, '//button[@name="processCarrier"]/span')
    type_pay_card = (By.XPATH, '//a[@title="Pay by bank wire"]')
    type_pay_check = (By.XPATH, '//a[@title="Pay by check."]')
    confirm_order_button = (By.XPATH, '//p[@id="cart_navigation"]//button[@type="submit"]/span')
    edit_new_address = (By.XPATH, '//input[@value="My address"]')


class LoginPagelocators:
    new_user_email = (By.XPATH, '//input[contains(@class, "is_required validate") and @id="email_create"]')
    create_user_button = (By.XPATH, '//div[@class="submit"]//span')
    mr_radio_button = (By.XPATH, '//div[@class="radio-inline"]//input[@id="id_gender1"]')
    first_name = (By.XPATH, '//input[contains(@onkeyup,"firstname")]')
    last_name = (By.XPATH, '//input[contains(@onkeyup,"lastname")]')
    email = (By.XPATH, '//div/input[@id="email"]')
    password = (By.XPATH, '//div/input[@type="password"]')
    birth_bate_d = (By.XPATH, '//select[@id="days"]')
    birth_bate_m = (By.XPATH, '//select[@id="months"]')
    birth_bate_y = (By.XPATH, '//select[@id="years"]')
    register_button = (By.XPATH, '//button[@id="submitAccount"]')
    fail_registration_alert = (By.XPATH, '//div[@class="alert alert-danger"]')
    success_registration = (By.XPATH, '//p[@class="alert alert-success"]')
    sign_out = (By.XPATH, '//a[@title="Log me out"]')
    twice_user = (By.XPATH, '//div[@id="create_account_error"]')
    verificated_user_email = (By.XPATH, '//input[@data-validate="isEmail" and @id="email"]')
    verificated_user_password = (By.XPATH, '//input[@data-validate="isPasswd" and @id="passwd"]')
    sign_in_verificated_user = (By.XPATH, '//button[@id="SubmitLogin"]/span')
    verify_user_logo = (By.XPATH, '//a[@class="account"]/span')

